# Generated by Django 4.1 on 2022-09-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='url',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
