# Generated by Django 4.1 on 2022-09-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_subreddit_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
