# Generated by Django 4.1 on 2022-09-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_comment_created_by_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subreddit',
            options={'ordering': ['subreddit_name']},
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
