# Generated by Django 4.1 on 2022-09-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
