# Generated by Django 4.1 on 2022-10-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_comment_score_alter_comment_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='parent',
        ),
    ]
