# Generated by Django 4.1 on 2022-10-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_rename_reply_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('admin_delete_post', 'admin delete post')]},
        ),
    ]
