# Generated by Django 4.1 on 2022-10-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'permissions': [('admin_delete_post', 'admin delete post')]},
        ),
    ]
