# Generated by Django 4.1 on 2022-10-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_subreddit_subreddit_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'permissions': [('admin_delete_comment', 'admin delete comment')]},
        ),
    ]
