# Generated by Django 4.1 on 2022-10-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_alter_comment_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
