# Generated by Django 4.1 on 2022-11-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image')], default='text', max_length=5),
            preserve_default=False,
        ),
    ]
