# Generated by Django 4.1 on 2022-11-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_alter_comment_comment_text_alter_post_post_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'permissions': [('admin_delete_comment', 'admin delete comment')]},
        ),
    ]
