# Generated by Django 4.1 on 2022-10-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_award_sent_by_award_purchased_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='tier',
            field=models.CharField(choices=[('gold', 'gold'), ('silver', 'silver'), ('bronze', 'bronze')], default='bronze', max_length=6),
        ),
    ]
