# Generated by Django 4.1 on 2022-10-28 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awards', '0002_alter_award_purchased_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='purchased_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_awards', to=settings.AUTH_USER_MODEL),
        ),
    ]
