# Generated by Django 4.1 on 2022-11-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_alter_award_purchased_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='purchased_by_username',
            field=models.CharField(default='blah', max_length=20),
            preserve_default=False,
        ),
    ]
